name: Variables Workflow
on: 
  workflow_dispatch:
env:
  MY_VARIABLE: ${{ secrets.MY_VARIABLE }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret Environment Variable
        run: echo "MY_VARIABLE is $MY_VARIABLE"